ExoShop/Models/ProductViewModel.cs
using Models.DataModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExoShop.Models
{
    public class ProductViewModel
    {
        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        [Range(0.0, 10000000000)]
        public double Price { get; set; }
        [Required]
        [DataType(DataType.ImageUrl)]
        public string ImageURL { get; set; }
    }
}

ExoShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Interfaces.Contexts;
using Interfaces.Logic;
using Logic.LogicObjects;
using ExoShop.Models;
using Models.DataModels;
using Exceptions.Product;

namespace ExoShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductLogic productLogic;
        private readonly IReviewLogic reviewLogic;

        public ProductController(IProductContext productContext, IReviewContext reviewContext)
        {
            productLogic = new ProductLogic(productContext);
            reviewLogic = new ReviewLogic(reviewContext);
        }

        private List<Product> GetAllProducts()
        {
            List<Product> products = new List<Product>();
            try
            {
                products = productLogic.GetAll();
                foreach (Product product in products)
                {
                    product.reviews = reviewLogic.GetAllByProduct(product);
                }
                return products;
            }
            catch (Exception)
            {
                return products;
            }
        }

        public IActionResult Info(int id)
        {
            Product product = GetAllProducts().Find(foundProduct => foundProduct.ID == id);
            if (product == null)
            {
                return RedirectToAction("Index", "Shop");
            }
            ViewBag.Reviews = reviewLogic.GetAllByProduct(product);
            ViewBag.Product = product;
            return View();
        }

        public IActionResult ProductPanel()
        {
            User loggedInUser = HttpContext.Session.GetUser();
            if (loggedInUser.IsAdmin)
            {
                ViewBag.Products = GetAllProducts();
                return View();
            }
            return RedirectToAction("Index", "Shop");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditProduct(int id, ProductViewModel model)
        {
            User loggedInUser = HttpContext.Session.GetUser();
            Product product = GetAllProducts().Find(foundProduct => foundProduct.ID == id);
            ViewBag.product = product;
            if (loggedInUser.IsAdmin)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        productLogic.EditProduct(new Product
                        {
                            ID = id,
                            Name = model.Name,
                            Description = model.Description,
                            ImageURL = model.ImageURL,
                            Price = model.Price,

                        });
                        return RedirectToAction("ProductPanel", "Product");
                    }
                    catch (UpdatingProductFailedException)
                    {
                        ModelState.AddModelError("", "Editing product failed, Try again.");
                        return RedirectToAction("ProductPanel", "Product");
                    }
                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int id)
        {
            User loggedInUser = HttpContext.Session.GetUser();
            if (loggedInUser.IsAdmin)
            {
                try
                {
                    Product product = GetAllProducts().Find(foundProduct => foundProduct.ID == id);
                    if (product.reviews.Any())
                    {
                        foreach (Review review in product.reviews)
                        {
                            reviewLogic.RemoveReview(review);
                        }
                    }
                    productLogic.RemoveProduct(product);
                    return RedirectToAction("ProductPanel", "Product");
                }
                catch (Exception)
                {
                    return RedirectToAction("ProductPanel", "Product");
                }
            }
            return RedirectToAction("ProductPanel", "Product");
        }

        public ActionResult AddProduct()
        {
            User loggedInUser = HttpContext.Session.GetUser();
            if (loggedInUser.IsAdmin)
            {
                return View();
            }
            return RedirectToAction("ProductPanel", "Product");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProduct(ProductViewModel model)
        {
            User loggedInUser = HttpContext.Session.GetUser();
            if (loggedInUser.IsAdmin)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        productLogic.AddProduct(new Product
                        {
                            Name = model.Name,
                            Description = model.Description,
                            ImageURL = model.ImageURL,
                            Price = model.Price,

                        });
                        return RedirectToAction("ProductPanel", "Product");
                    }
                    catch (AddingProductFailedException)
                    {
                        ModelState.AddModelError("", "Adding product failed, Try again.");
                        return RedirectToAction("ProductPanel", "Product");
                    }
                }
            }
            return View();
        }
    }
}

ExoShop/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exceptions.Review;
using ExoShop.Models;
using Interfaces.Contexts;
using Interfaces.Logic;
using Logic.LogicObjects;
using Microsoft.AspNetCore.Mvc;
using Models.DataModels;

namespace ExoShop.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IProductLogic productLogic;
        private readonly IReviewLogic reviewLogic;

        public ReviewController(IProductContext productContext, IReviewContext reviewContext)
        {
            productLogic = new ProductLogic(productContext);
            reviewLogic = new ReviewLogic(reviewContext);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddReview(int id, ReviewViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    User loggedInUser = HttpContext.Session.GetUser();
                    Product product = new Product
                    {
                        ID = id
                    };
                    Review review = new Review
                    {
                        Message = model.Message,
                        Stars = model.Stars,
                        Product = product,
                        User = loggedInUser
                    };
                    reviewLogic.AddReview(review);
                    return RedirectToAction("Info", "Product", new { id = id });
                }
                catch (AddingReviewFailedException)
                {
                    ModelState.AddModelError("", "Adding review failed, Try again.");
                    return RedirectToAction("Info", "Product", new { id = id });
                }
            }
            return RedirectToAction("Info", "Product", new { id = id });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveReview(int id)
        {
            try
            {
                Review review = new Review
                {
                    ID = id
                };
                reviewLogic.RemoveReview(review);
                return RedirectToAction("Info", "Product", new { id = id });
            }
            catch (RemovingReviewFailedException)
            {
                return RedirectToAction("Info", "Product", new { id = id });
            }
        }
    }
}

ExoShop/Controllers/WishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exceptions.Wishes;
using Interfaces.Contexts;
using Interfaces.Logic;
using Logic.LogicObjects;
using Microsoft.AspNetCore.Mvc;
using Models.DataModels;

namespace ExoShop.Controllers
{
    public class WishController : Controller
    {
        private readonly IProductLogic productLogic;
        private readonly IWishLogic wishLogic;

        public WishController(IProductContext productContext, IWishContext wishContext)
        {
            productLogic = new ProductLogic(productContext);
            wishLogic = new WishLogic(wishContext);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddToWishes(int id)
        {
            try
            {
                User loggedInUser = HttpContext.Session.GetUser();
                wishLogic.AddToWishList(productLogic.GetProductById(id), loggedInUser);
                HttpContext.Session.UpdateUser(loggedInUser);
                return RedirectToAction("Index", "Shop");
            }
            catch (AddingWishFailedException)
            {
                return RedirectToAction("Index", "Shop");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveFromWishes(int id)
        {
            try
            {
                User loggedInUser = HttpContext.Session.GetUser();
                wishLogic.RemoveFromWishList(productLogic.GetProductById(id), loggedInUser);
                HttpContext.Session.UpdateUser(loggedInUser);
                return RedirectToAction("Index", "User");
            }
            catch (RemovingWishesFailedException)
            {
                return RedirectToAction("Index", "User");
            }
        }
    }
}

ExoShop/Views/Product/AddProduct.cshtml
@model ExoShop.Models.ProductViewModel

@{
    ViewData["Title"] = "Add Product";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProduct" asp-controller="Product">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="mainBtn">Create</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ExoShop/Views/Product/Edit.cshtml
@model ExoShop.Models.ProductViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProductViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ExoShop/Views/Product/EditProduct.cshtml
@model ExoShop.Models.ProductViewModel
@{
    ViewData["Title"] = "Edit Product";
}
<h1>Edit Product</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditProduct" asp-controller="Product">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" placeholder="@ViewBag.product.Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" placeholder="@ViewBag.product.Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" placeholder="@ViewBag.product.Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" placeholder="@ViewBag.product.ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="" asp-controller="Product" asp-action="ProductPanel">Back to Products Panel</a>
</div>

ExoShop/Views/Product/Info.cshtml
@model ExoShop.Models.ReviewViewModel
@using Models.DataModels
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Product Information";
    List<Review> reviews = ViewBag.Reviews;
}
<h2>Product Information</h2>
<hr />
<div class="container">
    <div class="col-md-12">
        <div class="container service1-items col-sm-2 col-md-2 pull-left">
            <center>
                <img src="@ViewBag.Product.ImageURL" class="product-image" alt="@ViewBag.Product.Name">
            </center>
        </div>
        <div class="product-title">@ViewBag.Product.Name</div>
        <div class="product-desc">@ViewBag.Product.Description</div>
        <div class="product-rating">
            @for (int i = 0; i < 5; i++)
            {
                if (reviews.Any())
                {
                    if (i < reviews.Average(review => review.Stars))
                    {
                        <span class="fa fa-star checked"></span>
                    }
                    else
                    {
                        <span class="fa fa-star"></span>
                    }
                }
                else
                {
                    <span class="fa fa-star"></span>
                }
            }
            <div class="product-price">€@ViewBag.Product.Price</div>
        </div>
        <div class="btn-group cart">
            <form asp-action="AddToCart">

                <button type="submit" method="post" class="btn btn-success" asp-controller="Cart"
                        asp-action="AddToCart" asp-route-id="@ViewBag.Product.ID">
                    Add to Cart <i class="fa fa-cart-plus"></i>
                </button>
            </form>
        </div>
        <div class="btn-group wishlist">
            <form asp-action="AddToWishes">
                <button type="submit" method="post" class="btn btn-danger" asp-controller="Wish"
                        asp-action="AddToWishes" asp-route-id="@ViewBag.Product.ID">
                    Add to Wishlist <i class="fa fa-heart red"></i>
                </button>
            </form>
        </div>
    </div>
</div>
<hr />
<h4>Reviews</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                User
            </th>
            <th>
                Review
            </th>
            <th>
                Rating
            </th>
            @if (Context.Session.GetUser().IsAdmin)
            {
                <th>
                    Action
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (Review review in ViewBag.Reviews)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => review.User.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => review.Message)
                </td>
                <td>
                    @for (int i = 0; i < 5; i++)
                    {
                        if (i < review.Stars)
                        {
                            <span class="fa fa-star checked"></span>
                        }
                        else
                        {
                            <span class="fa fa-star"></span>
                        }
                    }
                </td>
                @if (Context.Session.GetUser().IsAdmin)
                {
                    <th>
                        <form asp-action="RemoveReview">
                            <button type="submit" method="post" class="mainBtn" asp-controller="Review"
                                    asp-action="RemoveReview" asp-route-id="@review.ID">
                                Remove <i class="fa fa-trash"></i>
                            </button>
                        </form>
                    </th>
                }
            </tr>
        }
    </tbody>
</table>
<hr />
<h4>Leave Review</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddReview" asp-controller="Review">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" placeholder="Short Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stars" class="control-label"></label>
                <input asp-for="Stars" placeholder="Amount of Stars out of 5" class="form-control" />
                <span asp-validation-for="Stars" class="text-danger"></span>
            </div>
            <button type="submit" method="post" class="mainBtn" asp-controller="Review"
                    asp-action="AddReview" asp-route-id="@ViewBag.Product.ID">
                Add Review
            </button>
        </form>
    </div>
</div>
<hr />

ExoShop/Views/Product/ProductPanel.cshtml
@using Models.DataModels
@{
    ViewData["Title"] = "Product Panel";
}
<link rel="stylesheet" href="~/css/site.css" />

<h4>Admin Panel</h4>
<div>
    <p>Wil je een nieuw product aanmaken?</p>
    <form asp-action="AddProduct">
        <button type="submit" class="mainBtn" asp-controller="Product"
         asp-action="AddProduct">Add Product</button>
    </form>
</div>
@foreach (Product product in ViewBag.Products)
{
    <div class="container">
        <div class="product-card">
            <img src="@product.ImageURL" class="product-image" alt="@product.Name">
            <h2 id="@product.ID">@product.Name</h2>
            <p class="price">€@product.Price</p>
            <p>@product.Description</p>
            <form asp-action="EditProduct">
                <button type="submit" class="btn btn-danger" asp-controller="Product"
                        asp-action="EditProduct" asp-route-id="@product.ID">
                    Edit Product
                </button>
            </form>
            <br />
            <form asp-action="DeleteProduct">
                <button type="submit" method="post" class="btn btn-danger" asp-controller="Product"
                        asp-action="DeleteProduct" asp-route-id="@product.ID">
                    Delete Product
                </button>
            </form>
        </div>
    </div>
}